Repository werkbot/silverstripe-module-newsletter, pull requests merged in 2022-12, with the labels that each got.

#33 improvements: support branch fixes, removed set-output
  .github/workflows/changelog.yml
  .github/workflows/draftrelease.yml
  .github/workflows/publish_release_draft.yml
  .github/workflows/sync_develop_with_master.yml
Labels: patch

#35 Added Shortcode method
  _config.php
  src/NewsletterPageExtender.php
  src/NewsletterShortcodeProvider.php
Labels: feature, major

#36 Release/2.1.0
  _config.php
  src/NewsletterPageExtender.php
  src/NewsletterShortcodeProvider.php
Labels: enhancement, feature, patch

#37 Fixed Variable
  src/NewsletterShortcodeProvider.php
Labels: patch
